name: Deploy frontend to staging

on:
  workflow_dispatch:
  push:
    branches:
      - staging
    paths-ignore:
      - 'supabase/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: staging

    env:
      CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_KEY}}
      VITE_CLIENT_URL: ${{vars.CLIENT_URL}}
      VITE_SERVER_URL: ${{vars.SERVER_URL}}
      VITE_SUPABASE_ID: ${{secrets.SUPABASE_PROJECT_ID}}
      VITE_SUPABASE_URL: ${{secrets.SUPABASE_URL}}
      VITE_SUPABASE_ANON_KEY: ${{secrets.SUPABASE_ANON_KEY}}
      VITE_SPOTIFY_ID: ${{secrets.SPOTIFY_ID}}
      VITE_HCAP_KEY: ${{secrets.HCAP_KEY}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install packages
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploying
      run: npx wrangler pages deploy ./dist --project-name musicprofile --branch web-staging
    
