name: Deploy frontend to staging

on:
  push:
    branches:
      - staging
    paths-ignore:
      - 'supabase/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_KEY}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install packages
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploying
      run: npx wrangler pages deploy ./dist --project-name musicprofile --branch web-staging
    
